[workspace]
members = ["boya-g192"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
bitflags = "2"
bytemuck = "1"
byteorder = "1"
itertools = "0.13"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
saturating_cast = "0.1"
thiserror = "2"
