[workspace]
members = ["boya-g192", "boya-g722", "boya-g729"]
resolver = "3"

[workspace.dependencies]
anyhow = "1"
bitflags = "2"
bitvec = "1"
byteorder = "1"
hex = "0.4"
itertools = "0.14"
num = "0.4"
saturating_cast = "0.1"
thiserror = "2"
